project_id = "krpvggbewyqamldhvmyk"

[functions.search-market-price]
verify_jwt = false

[functions.process-nfe]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.database-backup]
verify_jwt = false

[functions.create-auth-for-existing-users]
verify_jwt = false

[functions.migrate-base]
verify_jwt = false

[functions.populate-demo-data]
verify_jwt = false

[functions.create-test-user]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.asaas-customer-portal]
verify_jwt = false

[functions.asaas-cancel-subscription]
verify_jwt = false
